version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Easy IMM - Comprehensive example for Intersight

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>"
  ```


  {{ .Requirements }}
  {{ .Providers }}
  
  ## NOTE:
  **When the Data is merged from the YAML files it will run through modules in a for_each loop.  Sensitive Variables cannot be added to a for_each loop, use the variables below to add sensitive values for policies.**

  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false

settings:
  read-comments: false