---
intersight:
    policies:
      power:
        - name: 9508
          power_allocation: 8400
        - name: server
          power_restore: LastState
      thermal:
        - name: 9508
          fan_control_mode: Balanced
