---
#===========================================
#   Policies -> environment - Variables
#===========================================
default: # Name of the Organization
  policies:
    power:
      - description: 5108 Power Policy
        name: "5108"
        power_redundancy: Grid
      - description: 9508 Power Policy
        name: "9508"
        power_allocation: 5600
        power_redundancy: Grid
      - description: Server Power Policy
        name: Server
        power_redundancy: Grid
        power_restore: LastState
    thermal:
      - description: 5108 Thermal Policy
        fan_control_mode: Balanced
        name: "5108"
      - description: 9508 Thermal Policy
        fan_control_mode: Balanced
        name: "9508"
