---
#===========================================
#   Policies -> environment - Variables
#===========================================
intersight:
  policies:
    power:
      - description: 5108 Power Policy
        name: '5108'
        power_redundancy: Grid
      - description: 9508 Power Policy
        dynamic_power_rebalancing: Enabled
        name: '9508'
        power_allocation: 8400
        power_redundancy: Grid
        power_save_mode: Enabled
      - description: Server Power Policy
        name: Server
        power_priority: Low
        power_profiling: Enabled
        power_redundancy: Grid
        power_restore: LastState
    thermal:
      - description: 5108 Thermal Policy
        fan_control_mode: Balanced
        name: '5108'
      - description: 9508 Thermal Policy
        fan_control_mode: Balanced
        name: '9508'
